language:
- generic
dist: trusty
sudo: true
addons:
  apt:
    packages:
    - texlive-latex-extra
    - texlive-luatex
    - cm-super
    - texlive-bibtex-extra
    - latexmk
    - tex4ht
    - biber
    - texlive-fonts-recommended
    - texlive-lang-italian
    - latex-xcolor
    - texlive-publishers
    - pgf
    - lmodern
    - latex-beamer
script:
- make -B -j2
after_failure:
- cat report/GameBankReport.log
- cat presentation/GameBankPresentation.log
before_deploy:
- git fetch --tags
